-- MySQL Script generated by MySQL Workbench
-- Tue Aug 27 21:09:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alunos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Alunos` (
  `idAlunos` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Data_nascimento` DATE NULL,
  `CPF` VARCHAR(11) NOT NULL COMMENT 'CPF vachar no tamanho de 11 pq quero apenas os números e sem formatação (com pontos e traços)',
  `endereco` VARCHAR(45) NULL,
  `telefone` VARCHAR(15) NULL COMMENT 'Telefone vachar(15) com formatação e código do país',
  PRIMARY KEY (`idAlunos`, `CPF`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aula` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Aula` (
  `idAula` INT NOT NULL AUTO_INCREMENT,
  `ID_disciplina` INT NOT NULL,
  `ID_Professor` INT NOT NULL,
  `data` DATE NOT NULL,
  `time` TIME NOT NULL,
  PRIMARY KEY (`idAula`, `ID_disciplina`, `ID_Professor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Disciplinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Disciplinas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Disciplinas` (
  `idDisciplinas` INT NOT NULL AUTO_INCREMENT,
  `ID_curso` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `creditos` VARCHAR(45) NULL COMMENT 'creditos que a disciplina deu',
  PRIMARY KEY (`idDisciplinas`, `ID_curso`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Professor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Data_nascimento` DATE NULL,
  `CPF` VARCHAR(11) NOT NULL COMMENT 'CPF vachar no tamanho de 11 pq quero apenas os números e sem formatação (com pontos e traços)',
  `endereco` VARCHAR(45) NULL,
  `telefone` VARCHAR(15) NULL COMMENT 'Telefone vachar(15) com formatação e código do país',
  PRIMARY KEY (`idProfessor`, `CPF`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `creditosTotal` INT NOT NULL COMMENT 'Nescessario creditos totais do curso',
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `matriculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matriculas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `matriculas` (
  `idmatriculas` INT NOT NULL AUTO_INCREMENT,
  `id_aluno` INT NOT NULL,
  `ID_disciplina` INT NOT NULL,
  `data_matricula` DATE NOT NULL,
  PRIMARY KEY (`idmatriculas`, `id_aluno`, `ID_disciplina`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
